### ISSUE TITLE
Feature request: Boot even though test scrape fails

### ISSUE THREAD

**Issue by andrewhowdencom** [jonnenauha/prometheus_varnish_exporter#18]
Currently this service is running in our production environment, exporting stats nicely from Varnish. However, during a machine reboot, the test scrape can fail (if it boots faster than varnish), and the application will fail. 

This is a stub to consider not failing, but simply exposing a metric that indicates prometheus is down. This allows it to come "up" later as Varnish also boots.

Note: Ideally, i do not want to simply introduce a dependency in systemd on the varnish unit; in my mind, the exporter should simply try and export metrics on demand, rather than requiring a valid varnish instance on boot. This more accurately represents the state where applications are natively instrumented, as when collection fails, it will be attempted a short time later.

**Comment by jonnenauha** [comment]
Great idea. I would suggest it retries with increasing sleeps, before doing a fatal exit.

#1 fail > sleep 5 secs
#2 fail > sleep 10 secs
#3 fail > sleep 30 secs
#4 fail > fatal exit the process (exit code 1)

Would this suit your needs? I would rather not change the behavior so that it will retry the scrape forever. I would like it to exit out the process if is cant connect in that time. I know this "random" sleep might not be optimal, we could make it more robust, but again I would not like to lose the behavior that it fatals out.

Those 45 seconds should be plenty enough to get varnish up and running?

I actually have similar situation at my work (for what I made this exported for). But varnish service is started up by the init system. I then have supervisord that starts (later than varnish) that runs the monitor. So I never got this "timing" issue. And actually I might have this situation but supervisord will restart it about 5 times with 5 sec sleeps (or something to that effect) so never would have noticed it.

**Comment by jonnenauha** [comment]
Hmm. Then again, this "run forever" mode could be enabled with a cmd line option.

Lets say `-wait` would make it poll the initial scrape forever, sleeping 5 seconds in between. Might be better for users such as yourself? Less complexity as well.

**Comment by andrewhowdencom** [comment]
I think the ideal solution would be to skip the initial scrape, and just lazily initialise. However, given the constraint of "requires initial scrape" (I haven't  looked at code) I think exponential backoff with jitter, and a max retry limit is the ideal model for this: 

https://www.awsarchitectureblog.com/2015/03/backoff.html

k8s uses this model for restarts, for example. That seems like a lot of work though. I'd be happy with just a loop.  

Re. metrics; I think I'd return a 200 if the `up` metric exists (but have the "up" metric return a 0, or if it does not and we cannot determine any metrics a `500`. That clearly conveys something is badly wrong, and Promethus will pick that up with it's own `up` metrics (it does this anyway when it can't query stuff, but it might be nice to be able to convey "something is wrong" with exporter)

It's also worth thinking about whether this is even right to handle in the exporter itself, or whether i should do this in systemd. https://serverfault.com/questions/736624/systemd-service-automatic-restart-after-startlimitinterval

**Comment by jonnenauha** [comment]
You'll get the behavior you wanted with the next release. Just add `-no-exit` param to where you are running this exporter.

I'll tag it once I implement support varnish 5.2 as it changes varnishstat output. If you are in a hurry just build HEAD by hand.
