### ISSUE TITLE
Backends without health probe are reported as unhappy

### ISSUE THREAD

**Issue by vStone** [jonnenauha/prometheus_varnish_exporter#28]
* **Varnish** `4.1.9`
* **prometheus_varnish_exporter** `1.4`

------------------
The prometheus exporter does not report backends without health-check as healthy. You could make the argument that if they don't have a health-check, there is no way to know if they are healthy so the result should be 0.
That being said: I can't figure out any way to create a rule that works for both backends with health-checks and backends without. The simplest solution would be to have backends without healthcheck be reported as healthy.

**Comment by jonnenauha** [comment]
Hmm, yes I suppose you are right that it would make sense to report them as helthy. However when I see the unhealthy status, I don't know if its because of lack of health checks not configured or if the backend is really down. I would need access and parse the vlc in order to determine that, and that would make my impl a lot more complex.

I don't know a way to ask varnish if something has checks enabled or not. I would just blindly always report all are happy :) 

I believe you could make prometheys side rules to drop the health metric for backends without health checks. I don't know exactly how to do this, but I believe they have filtering rules to acoomplish this.
