### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by steve-stonehouse** [jonnenauha/prometheus_varnish_exporter#71]
* **Varnish** `-`
* **prometheus_varnish_exporter** `-`

------------------

Can a new release containing the fix for https://github.com/jonnenauha/prometheus_varnish_exporter/commit/67294c8cc8e0bf4c86045a160c39bb12d03b33a9 be created please?

I am also experiencing this issue. Thanks

**Comment by LukeHandle** [comment]
Hi there, over in https://github.com/mittwald/kube-httpcache/issues/81 this issue was raised and whether there will be another release created.

Fully understand other priorities/commitments, but a vague answer of "there are plans for a future release when I can put some time in" would be absolutely fine. If on the other hand that's unlikely for the next couple of months, that's also helpful as they can look at a temporary fork/release (though obviously not the route anyone wants to pursue). 

Thank you for the work you've put in here!

**Comment by jonnenauha** [comment]
Thanks for the nudge guys, sorry it took so long to get this out :I

https://github.com/jonnenauha/prometheus_varnish_exporter/releases/tag/1.6.1
